##
# Build
##
FROM golang:alpine AS builder
LABEL stage=builder
WORKDIR /app
# Install dependency
COPY go.mod go.sum ./
RUN go mod download
# Build project
COPY . .
RUN go build -o server cmd/server/main.go

##
# Run image
##
FROM alpine
WORKDIR /app
COPY --from=builder /app/server ./server
COPY data/quotes.txt /app/data/quotes.txt
CMD ./server
