##
# Build
##
FROM golang:alpine AS builder
LABEL stage=builder
WORKDIR /app
# Install dependency
COPY go.mod go.sum ./
RUN go mod download
# Build project
COPY . .
RUN go build -o client cmd/client/main.go

##
# Run image
##
FROM alpine
WORKDIR /app
COPY --from=builder /app/client ./client
CMD ./client
